### PR TITLE
String#=~ faster than String#match

### PR DESCRIPTION
**Pull request by schneems**
If you're only looking for presence of a match and don't need the matchdata, use String#=~ 

https://github.com/schneems/rails/commit/1bf50badd943e684a56a03392ef0ddafefca0ad7#commitcomment-12572839

### CODE REVIEW

**Comment by Arcovion** [comment]
String#=== is faster

**Comment by Arcovion** [comment]
Regexp#=== is a bit faster

**Comment by schneems** [comment]
Yep

```
Calculating -------------------------------------
           String#=~    66.023k i/100ms
        String#match    60.124k i/100ms
          String#===    70.747k i/100ms
-------------------------------------------------
           String#=~      1.798M (±10.3%) i/s -      8.913M
        String#match      1.374M (± 9.7%) i/s -      6.854M
          String#===      1.847M (± 9.8%) i/s -      9.197M
```

Seems good. How should I report this? I would like to have all 3 examples in the code and reported.

**Comment by Arcovion** [comment]
Edited my comment as String#=== was wrong, you want Regexp#===. Added example of how it might look...

**Comment by JuanitoFatas** [comment]
How about list all possibilities?

```ruby
require "benchmark/ips"

def fastest
  "foo".freeze === /boo/
end

def faster
  "foo".freeze =~ /boo/
end

def fast
  /boo/ === "foo".freeze
end

def slow
  "foo".freeze.match(/boo/)
end

Benchmark.ips do |x|
  x.report("String#===") { fastest }
  x.report("Regexp#===") { faster }
  x.report("String#=~") { fast }
  x.report("String#match") { slow }
  x.compare!
end
```

```
ruby -v code/string/match-vs-=\~.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Calculating -------------------------------------
          String#===   143.440k i/100ms
          Regexp#===    94.853k i/100ms
           String#=~    91.999k i/100ms
        String#match    88.397k i/100ms
-------------------------------------------------
          String#===      5.637M (± 7.4%) i/s -     28.114M
          Regexp#===      2.599M (± 5.4%) i/s -     12.995M
           String#=~      2.318M (± 7.7%) i/s -     11.592M
        String#match      1.905M (± 8.4%) i/s -      9.458M

Comparison:
          String#===:  5637360.8 i/s
          Regexp#===:  2599326.4 i/s - 2.17x slower
           String#=~:  2318149.8 i/s - 2.43x slower
        String#match:  1905484.8 i/s - 2.96x slower
```

:question:

**Comment by Arcovion** [comment]
String#=== doesn't work, it's not the correct result.

**Comment by JuanitoFatas** [comment]
> String#=== doesn't work, it's not the correct result.

Yup. The https://github.com/JuanitoFatas/fast-ruby/pull/59#issuecomment-128562623 is wrong.

--

Let's keep this simple since the regexp need to flip the string to be compared to the end. Which is counterintuitive

**Comment by schneems** [comment]
It's a pretty big speed boost, we would have to rename it to `Regexp#===` and we could put a warning in about not switching the arguments cause you'll get the wrong results

**Pull request merged**
