### PR TITLE
Add Regexp#=== to match and =~ comparison

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Follow up of https://github.com/JuanitoFatas/fast-ruby/pull/59

On my machine [`String#=~` is faster than `Regexp#===`](https://github.com/JuanitoFatas/fast-ruby/blob/d41c78f9ded0ab0b59a7884811bbad97897adaf5/README.md#regexp-vs-stringmatch-vs-string-code-).

What do you guys think?

/cc @Arcovion @schneems 

--

https://github.com/schneems/rails/commit/1bf50badd943e684a56a03392ef0ddafefca0ad7#commitcomment-12572839
https://github.com/schneems/rails/commit/752432e82f3032e96ba609b65437cd8e8b8d3939

### CODE REVIEW

**Comment by schneems** [comment]
Confirm

```
Calculating -------------------------------------
           String#=~    67.365k i/100ms
          Regexp#===    63.076k i/100ms
        String#match    56.745k i/100ms
-------------------------------------------------
           String#=~      1.645M (±12.9%) i/s -      8.084M
          Regexp#===      1.511M (±12.1%) i/s -      7.443M
        String#match      1.208M (±15.2%) i/s -      5.901M

```

Weird, I could have sworn I saw it faster earlier

**Comment by Arcovion** [comment]
Hmm, yea very little in it. They do different things too, with Regexp#=== returning a boolean (which is handy, as before I knew that I used `!!str[/match/]`).
I think it's good to include, to show that they are equally fast.

**Comment by schneems** [comment]
String#=~ is `(1.645 - 1.511 ) / 1.511 #=>` 8 % faster

**Comment by Arcovion** [comment]
Same benchmark:
```
Calculating -------------------------------------
           String#=~   138.285k i/100ms
          Regexp#===   130.622k i/100ms
        String#match   112.077k i/100ms
-------------------------------------------------
           String#=~      3.273M (± 2.6%) i/s -     16.456M
          Regexp#===      3.406M (± 4.3%) i/s -     16.981M
        String#match      2.714M (± 2.8%) i/s -     13.561M

Comparison:
          Regexp#===:  3406168.4 i/s
           String#=~:  3273161.4 i/s - 1.04x slower
        String#match:  2714176.6 i/s - 1.25x slower
```
```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
```
Mine has the lowest standard deviation @ ± 4.3%, also higher IPS
Essentially equal for me.

**Comment by JuanitoFatas** [comment]
Merged in https://github.com/JuanitoFatas/fast-ruby/commit/69c1ed1ab4ef5a6c64b5ad59c84167e6194c9b0c. Thanks everyone.

**Comment by SamSaffron** [comment]
Got to add `"test".match?(/e/)` as well cause that is fastest.

**Pull request closed without merging**
