### PR TITLE
 Add `String#delete_prefix` and `delete_suffix` benchmarks

### PR DESCRIPTION
**Pull request by bdewater**

### CODE REVIEW

**Comment by Arcovion** [comment]
Build is failing due to a bug, if you wouldn't mind amending your last commit to:
```yaml
- rvm: 2.5.1
  before_install:
    # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
    - gem update --system
```
According to https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443 that should fix it!

**Comment by bdewater** [comment]
Thanks @Arcovion  !

**Comment by Arcovion** [comment]
Whoops. I've never actually modified `travis.yml`, I guess it needs to be done like:
```yaml
matrix:
  include:
    - rvm: 2.5.1
      before_install:
        # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
        - gem update --system
```
If I'm [reading this correctly](https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs), it'll run the `gem update --system` only for `2.5.1`; you can then remove the other mention of `- 2.5.1` above.

OR we can simply add `2.5.1` to the `allowed_failures` list for now and remove it once the bug is fixed:
```yaml
 matrix:
   allow_failures:
     - rvm: 2.5.1
```

**Comment by Arcovion** [comment]
Thanks! 💖

**Pull request merged**
